# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2026.2.2\bin\cmake\win\x64\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2026.2.2\bin\cmake\win\x64\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Projects\BMSTU

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Projects\BMSTU\cmake-build-debug

# Include any dependencies generated for this target.
include CMakeFiles/README.md.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/README.md.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/README.md.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/README.md.dir/flags.make

CMakeFiles/README.md.dir/codegen:
.PHONY : CMakeFiles/README.md.dir/codegen

CMakeFiles/README.md.dir/lab1.1.cpp.obj: CMakeFiles/README.md.dir/flags.make
CMakeFiles/README.md.dir/lab1.1.cpp.obj: C:/Projects/BMSTU/lab1.1.cpp
CMakeFiles/README.md.dir/lab1.1.cpp.obj: CMakeFiles/README.md.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Projects\BMSTU\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/README.md.dir/lab1.1.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/README.md.dir/lab1.1.cpp.obj -MF CMakeFiles\README.md.dir\lab1.1.cpp.obj.d -o CMakeFiles\README.md.dir\lab1.1.cpp.obj -c C:\Projects\BMSTU\lab1.1.cpp

CMakeFiles/README.md.dir/lab1.1.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/README.md.dir/lab1.1.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Projects\BMSTU\lab1.1.cpp > CMakeFiles\README.md.dir\lab1.1.cpp.i

CMakeFiles/README.md.dir/lab1.1.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/README.md.dir/lab1.1.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Projects\BMSTU\lab1.1.cpp -o CMakeFiles\README.md.dir\lab1.1.cpp.s

CMakeFiles/README.md.dir/lab1.2.cpp.obj: CMakeFiles/README.md.dir/flags.make
CMakeFiles/README.md.dir/lab1.2.cpp.obj: C:/Projects/BMSTU/lab1.2.cpp
CMakeFiles/README.md.dir/lab1.2.cpp.obj: CMakeFiles/README.md.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Projects\BMSTU\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/README.md.dir/lab1.2.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/README.md.dir/lab1.2.cpp.obj -MF CMakeFiles\README.md.dir\lab1.2.cpp.obj.d -o CMakeFiles\README.md.dir\lab1.2.cpp.obj -c C:\Projects\BMSTU\lab1.2.cpp

CMakeFiles/README.md.dir/lab1.2.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/README.md.dir/lab1.2.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Projects\BMSTU\lab1.2.cpp > CMakeFiles\README.md.dir\lab1.2.cpp.i

CMakeFiles/README.md.dir/lab1.2.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/README.md.dir/lab1.2.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Projects\BMSTU\lab1.2.cpp -o CMakeFiles\README.md.dir\lab1.2.cpp.s

CMakeFiles/README.md.dir/labb1.1.cpp.obj: CMakeFiles/README.md.dir/flags.make
CMakeFiles/README.md.dir/labb1.1.cpp.obj: C:/Projects/BMSTU/labb1.1.cpp
CMakeFiles/README.md.dir/labb1.1.cpp.obj: CMakeFiles/README.md.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Projects\BMSTU\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building CXX object CMakeFiles/README.md.dir/labb1.1.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/README.md.dir/labb1.1.cpp.obj -MF CMakeFiles\README.md.dir\labb1.1.cpp.obj.d -o CMakeFiles\README.md.dir\labb1.1.cpp.obj -c C:\Projects\BMSTU\labb1.1.cpp

CMakeFiles/README.md.dir/labb1.1.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/README.md.dir/labb1.1.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Projects\BMSTU\labb1.1.cpp > CMakeFiles\README.md.dir\labb1.1.cpp.i

CMakeFiles/README.md.dir/labb1.1.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/README.md.dir/labb1.1.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Projects\BMSTU\labb1.1.cpp -o CMakeFiles\README.md.dir\labb1.1.cpp.s

CMakeFiles/README.md.dir/labb1.2.cpp.obj: CMakeFiles/README.md.dir/flags.make
CMakeFiles/README.md.dir/labb1.2.cpp.obj: C:/Projects/BMSTU/labb1.2.cpp
CMakeFiles/README.md.dir/labb1.2.cpp.obj: CMakeFiles/README.md.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir=C:\Projects\BMSTU\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Building CXX object CMakeFiles/README.md.dir/labb1.2.cpp.obj"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/README.md.dir/labb1.2.cpp.obj -MF CMakeFiles\README.md.dir\labb1.2.cpp.obj.d -o CMakeFiles\README.md.dir\labb1.2.cpp.obj -c C:\Projects\BMSTU\labb1.2.cpp

CMakeFiles/README.md.dir/labb1.2.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/README.md.dir/labb1.2.cpp.i"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E C:\Projects\BMSTU\labb1.2.cpp > CMakeFiles\README.md.dir\labb1.2.cpp.i

CMakeFiles/README.md.dir/labb1.2.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/README.md.dir/labb1.2.cpp.s"
	C:\PROGRA~1\JETBRA~1\CLION2~1.2\bin\mingw\bin\C__~1.EXE $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S C:\Projects\BMSTU\labb1.2.cpp -o CMakeFiles\README.md.dir\labb1.2.cpp.s

# Object files for target README.md
README_md_OBJECTS = \
"CMakeFiles/README.md.dir/lab1.1.cpp.obj" \
"CMakeFiles/README.md.dir/lab1.2.cpp.obj" \
"CMakeFiles/README.md.dir/labb1.1.cpp.obj" \
"CMakeFiles/README.md.dir/labb1.2.cpp.obj"

# External object files for target README.md
README_md_EXTERNAL_OBJECTS =

README.md.exe: CMakeFiles/README.md.dir/lab1.1.cpp.obj
README.md.exe: CMakeFiles/README.md.dir/lab1.2.cpp.obj
README.md.exe: CMakeFiles/README.md.dir/labb1.1.cpp.obj
README.md.exe: CMakeFiles/README.md.dir/labb1.2.cpp.obj
README.md.exe: CMakeFiles/README.md.dir/build.make
README.md.exe: CMakeFiles/README.md.dir/linkLibs.rsp
README.md.exe: CMakeFiles/README.md.dir/objects1.rsp
README.md.exe: CMakeFiles/README.md.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir=C:\Projects\BMSTU\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_5) "Linking CXX executable README.md.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\README.md.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/README.md.dir/build: README.md.exe
.PHONY : CMakeFiles/README.md.dir/build

CMakeFiles/README.md.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\README.md.dir\cmake_clean.cmake
.PHONY : CMakeFiles/README.md.dir/clean

CMakeFiles/README.md.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" C:\Projects\BMSTU C:\Projects\BMSTU C:\Projects\BMSTU\cmake-build-debug C:\Projects\BMSTU\cmake-build-debug C:\Projects\BMSTU\cmake-build-debug\CMakeFiles\README.md.dir\DependInfo.cmake "--color=$(COLOR)" README.md
.PHONY : CMakeFiles/README.md.dir/depend

