# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.3

# compile CXX with C:/Program Files/JetBrains/CLion 2026.2.2/bin/mingw/bin/c++.exe
CXX_DEFINES = 

CXX_INCLUDES = 

CXX_FLAGS = -g -std=gnu++26 -fdiagnostics-color=always

